// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMFeZ5FReJkKtPi4yZmYBgtbgJV1YC2_I',
    appId: '1:975055358403:web:fd6c78a0ca3742e8f29576',
    messagingSenderId: '975055358403',
    projectId: 'interview-preparation-50bfb',
    authDomain: 'interview-preparation-50bfb.firebaseapp.com',
    storageBucket: 'interview-preparation-50bfb.appspot.com',
    measurementId: 'G-D8ZHXRFZEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIS5FJNFwHPdWwmEwugzKcSdNYcx7lv_o',
    appId: '1:975055358403:android:275525806079ff1ff29576',
    messagingSenderId: '975055358403',
    projectId: 'interview-preparation-50bfb',
    storageBucket: 'interview-preparation-50bfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNHis9QEcHhMlWwTGLOHauULMqbgTYgek',
    appId: '1:975055358403:ios:a0ad9d817a59d2fef29576',
    messagingSenderId: '975055358403',
    projectId: 'interview-preparation-50bfb',
    storageBucket: 'interview-preparation-50bfb.appspot.com',
    iosBundleId: 'com.example.interviewPreparation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNHis9QEcHhMlWwTGLOHauULMqbgTYgek',
    appId: '1:975055358403:ios:a0ad9d817a59d2fef29576',
    messagingSenderId: '975055358403',
    projectId: 'interview-preparation-50bfb',
    storageBucket: 'interview-preparation-50bfb.appspot.com',
    iosBundleId: 'com.example.interviewPreparation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMFeZ5FReJkKtPi4yZmYBgtbgJV1YC2_I',
    appId: '1:975055358403:web:a7767deca9916179f29576',
    messagingSenderId: '975055358403',
    projectId: 'interview-preparation-50bfb',
    authDomain: 'interview-preparation-50bfb.firebaseapp.com',
    storageBucket: 'interview-preparation-50bfb.appspot.com',
    measurementId: 'G-YE1SN3FCXY',
  );
}
